export const videos = [
  {
    id: 324393,
    title: 'Video awesome',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'test',
      email: 'test@test.com',
    },
  },
  {
    id: 1212121,
    title: 'Video super',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'tes',
      email: 'test@test.com',
    },
  },
  {
    id: 55555,
    title: 'Video nice',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'test',
      email: 'test@test.com',
    },
  },
  {
    id: 11111,
    title: 'Video perfect',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'test',
      email: 'test@test.com',
    },
  },
  {
    id: 324394,
    title: 'Video awesome',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'test',
      email: 'test@test.com',
    },
  },
  {
    id: 1212122,
    title: 'Video super',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'tes',
      email: 'test@test.com',
    },
  },
  {
    id: 55556,
    title: 'Video nice',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'test',
      email: 'test@test.com',
    },
  },
  {
    id: 11112,
    title: 'Video perfect',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'test',
      email: 'test@test.com',
    },
  },
  {
    id: 324395,
    title: 'Video awesome',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'test',
      email: 'test@test.com',
    },
  },
  {
    id: 1212123,
    title: 'Video super',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'tes',
      email: 'test@test.com',
    },
  },
  {
    id: 55557,
    title: 'Video nice',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'test',
      email: 'test@test.com',
    },
  },
  {
    id: 11113,
    title: 'Video perfect',
    description: 'This is something I love',
    views: 24,
    videoFile: 'https://archive.org/details/BigBuckBunny_124',
    creator: {
      id: 121212,
      name: 'test',
      email: 'test@test.com',
    },
  },
];
